-- Criação da tabela de lançamentos detalhados do Caixa Dinheiro
CREATE TABLE IF NOT EXISTS public.caixa_dinheiro_lancamentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    data date NOT NULL,
    descricao text NOT NULL,
    tipo text NOT NULL CHECK (tipo IN ('entrada', 'saida')),
    valores_json jsonb NOT NULL,
    valor_total numeric NOT NULL,
    user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.caixa_dinheiro_lancamentos ENABLE ROW LEVEL SECURITY;

-- Criar políticas de acesso para usuários autenticados
CREATE POLICY "Permitir leitura para usuários autenticados" 
ON public.caixa_dinheiro_lancamentos FOR SELECT TO authenticated USING (true);

CREATE POLICY "Permitir inserção para usuários autenticados" 
ON public.caixa_dinheiro_lancamentos FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Permitir atualização para usuários autenticados" 
ON public.caixa_dinheiro_lancamentos FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Permitir exclusão para usuários autenticados" 
ON public.caixa_dinheiro_lancamentos FOR DELETE TO authenticated USING (true);

-- Adicionar à publicação realtime do Supabase para sincronização instantânea
ALTER PUBLICATION supabase_realtime ADD TABLE public.caixa_dinheiro_lancamentos;
