-- 1. Categorias de Onboarding (dinâmicas)
CREATE TABLE IF NOT EXISTS public.onboarding_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL,
    type text NOT NULL DEFAULT 'checklist' CHECK (type IN ('checklist', 'text')),
    ordem integer NOT NULL DEFAULT 0
);

-- 2. Tópicos/Tarefas de Onboarding vinculadas a uma categoria
CREATE TABLE IF NOT EXISTS public.onboarding_topics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    category_id bigint NOT NULL REFERENCES public.onboarding_categories(id) ON DELETE CASCADE,
    title text NOT NULL,
    ordem integer NOT NULL DEFAULT 0
);

-- 3. Registro de conclusão dos tópicos por colaborador
CREATE TABLE IF NOT EXISTS public.onboarding_completions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    topic_id bigint NOT NULL REFERENCES public.onboarding_topics(id) ON DELETE CASCADE,
    completed boolean NOT NULL DEFAULT false,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE (profile_id, topic_id)
);

-- 4. Status do onboarding por colaborador
CREATE TABLE IF NOT EXISTS public.onboarding (
    id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    status text NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'em_andamento', 'concluido'))
);

-- Habilitar Row Level Security (RLS) para todas as tabelas
ALTER TABLE public.onboarding_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.onboarding_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.onboarding_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.onboarding ENABLE ROW LEVEL SECURITY;

-- Criar políticas de acesso para usuários autenticados para onboarding_categories
CREATE POLICY "Permitir leitura de categorias para autenticados" 
ON public.onboarding_categories FOR SELECT TO authenticated USING (true);

CREATE POLICY "Permitir inserção de categorias para autenticados" 
ON public.onboarding_categories FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Permitir atualização de categorias para autenticados" 
ON public.onboarding_categories FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Permitir exclusão de categorias para autenticados" 
ON public.onboarding_categories FOR DELETE TO authenticated USING (true);

-- Criar políticas de acesso para usuários autenticados para onboarding_topics
CREATE POLICY "Permitir leitura de tópicos para autenticados" 
ON public.onboarding_topics FOR SELECT TO authenticated USING (true);

CREATE POLICY "Permitir inserção de tópicos para autenticados" 
ON public.onboarding_topics FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Permitir atualização de tópicos para autenticados" 
ON public.onboarding_topics FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Permitir exclusão de tópicos para autenticados" 
ON public.onboarding_topics FOR DELETE TO authenticated USING (true);

-- Criar políticas de acesso para usuários autenticados para onboarding_completions
CREATE POLICY "Permitir leitura de conclusões para autenticados" 
ON public.onboarding_completions FOR SELECT TO authenticated USING (true);

CREATE POLICY "Permitir inserção de conclusões para autenticados" 
ON public.onboarding_completions FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Permitir atualização de conclusões para autenticados" 
ON public.onboarding_completions FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Permitir exclusão de conclusões para autenticados" 
ON public.onboarding_completions FOR DELETE TO authenticated USING (true);

-- Criar políticas de acesso para usuários autenticados para onboarding
CREATE POLICY "Permitir leitura de onboarding para autenticados" 
ON public.onboarding FOR SELECT TO authenticated USING (true);

CREATE POLICY "Permitir inserção de onboarding para autenticados" 
ON public.onboarding FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Permitir atualização de onboarding para autenticados" 
ON public.onboarding FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Permitir exclusão de onboarding para autenticados" 
ON public.onboarding FOR DELETE TO authenticated USING (true);

-- Adicionar as novas tabelas à publicação realtime para sincronização instantânea
ALTER PUBLICATION supabase_realtime ADD TABLE public.onboarding_categories;
ALTER PUBLICATION supabase_realtime ADD TABLE public.onboarding_topics;
ALTER PUBLICATION supabase_realtime ADD TABLE public.onboarding_completions;
ALTER PUBLICATION supabase_realtime ADD TABLE public.onboarding;
