-- ==============================================================================
-- SCRIPT SQL: Tabela de Registro de Tarefas Concluídas
-- Executar este script no Editor SQL do console do Supabase
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.tarefas_lojas_concluidas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    tarefa_id BIGINT NOT NULL REFERENCES public.tarefas_lojas(id) ON DELETE CASCADE,
    loja TEXT NOT NULL,
    data_referencia DATE NOT NULL,
    concluido_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    concluido_por TEXT
);

-- Criar índice para buscas rápidas por loja e data
CREATE INDEX IF NOT EXISTS idx_tarefas_concluidas_loja_data 
ON public.tarefas_lojas_concluidas(loja, data_referencia);

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.tarefas_lojas_concluidas ENABLE ROW LEVEL SECURITY;

-- Políticas RLS
DROP POLICY IF EXISTS "Permitir leitura tarefas_lojas_concluidas" ON public.tarefas_lojas_concluidas;
DROP POLICY IF EXISTS "Permitir inserção tarefas_lojas_concluidas" ON public.tarefas_lojas_concluidas;
DROP POLICY IF EXISTS "Permitir atualização tarefas_lojas_concluidas" ON public.tarefas_lojas_concluidas;
DROP POLICY IF EXISTS "Permitir deleção tarefas_lojas_concluidas" ON public.tarefas_lojas_concluidas;

CREATE POLICY "Permitir leitura tarefas_lojas_concluidas" ON public.tarefas_lojas_concluidas FOR SELECT USING (true);
CREATE POLICY "Permitir inserção tarefas_lojas_concluidas" ON public.tarefas_lojas_concluidas FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir atualização tarefas_lojas_concluidas" ON public.tarefas_lojas_concluidas FOR UPDATE USING (true);
CREATE POLICY "Permitir deleção tarefas_lojas_concluidas" ON public.tarefas_lojas_concluidas FOR DELETE USING (true);

-- Permissões
GRANT ALL ON TABLE public.tarefas_lojas_concluidas TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
