-- ==============================================================================
-- SCRIPT SQL: Criação e configuração da tabela 'tarefas_lojas' no Supabase
-- Executar este script no Editor SQL do console do Supabase
-- ==============================================================================

-- 1. Criação da Tabela
CREATE TABLE IF NOT EXISTS public.tarefas_lojas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    titulo TEXT NOT NULL,
    loja TEXT DEFAULT 'Todas'::text NOT NULL,
    tipo_repeticao TEXT DEFAULT 'diaria'::text NOT NULL,
    repeticao TEXT DEFAULT 'Todo dia'::text NOT NULL,
    dias_semana JSONB,
    dia_mes INT,
    descricao TEXT,
    criado_por TEXT
);

-- 2. Verificação e adição de colunas (caso a tabela já existisse parcialmente)
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tarefas_lojas' AND column_name='titulo') THEN
        ALTER TABLE public.tarefas_lojas ADD COLUMN titulo TEXT NOT NULL DEFAULT '';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tarefas_lojas' AND column_name='loja') THEN
        ALTER TABLE public.tarefas_lojas ADD COLUMN loja TEXT DEFAULT 'Todas'::text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tarefas_lojas' AND column_name='tipo_repeticao') THEN
        ALTER TABLE public.tarefas_lojas ADD COLUMN tipo_repeticao TEXT DEFAULT 'diaria'::text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tarefas_lojas' AND column_name='repeticao') THEN
        ALTER TABLE public.tarefas_lojas ADD COLUMN repeticao TEXT DEFAULT 'Todo dia'::text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tarefas_lojas' AND column_name='dias_semana') THEN
        ALTER TABLE public.tarefas_lojas ADD COLUMN dias_semana JSONB;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tarefas_lojas' AND column_name='dia_mes') THEN
        ALTER TABLE public.tarefas_lojas ADD COLUMN dia_mes INT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tarefas_lojas' AND column_name='descricao') THEN
        ALTER TABLE public.tarefas_lojas ADD COLUMN descricao TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tarefas_lojas' AND column_name='criado_por') THEN
        ALTER TABLE public.tarefas_lojas ADD COLUMN criado_por TEXT;
    END IF;
END $$;

-- 3. Habilitar RLS (Row Level Security)
ALTER TABLE public.tarefas_lojas ENABLE ROW LEVEL SECURITY;

-- 4. Excluir políticas antigas se existirem
DROP POLICY IF EXISTS "Permitir leitura tarefas_lojas" ON public.tarefas_lojas;
DROP POLICY IF EXISTS "Permitir inserção tarefas_lojas" ON public.tarefas_lojas;
DROP POLICY IF EXISTS "Permitir atualização tarefas_lojas" ON public.tarefas_lojas;
DROP POLICY IF EXISTS "Permitir deleção tarefas_lojas" ON public.tarefas_lojas;

-- 5. Criar Políticas RLS de Leitura, Escrita, Atualização e Deleção
CREATE POLICY "Permitir leitura tarefas_lojas" ON public.tarefas_lojas FOR SELECT USING (true);
CREATE POLICY "Permitir inserção tarefas_lojas" ON public.tarefas_lojas FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir atualização tarefas_lojas" ON public.tarefas_lojas FOR UPDATE USING (true);
CREATE POLICY "Permitir deleção tarefas_lojas" ON public.tarefas_lojas FOR DELETE USING (true);

-- 6. Conceder permissões de acesso
GRANT ALL ON TABLE public.tarefas_lojas TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
