INSERT INTO cadastro_produtos (nome, categoria, ativo, is_sabor, is_preparacao, unidade_venda)
VALUES 
('Abacate', 'Gelato', true, true, false, 'kg'),
('Abacaxi com Hortelã', 'Gelato', true, true, false, 'kg'),
('Avelâ', 'Gelato', true, true, false, 'kg'),
('Banana Água', 'Gelato', true, true, false, 'kg'),
('Banoffe', 'Gelato', true, true, false, 'kg'),
('Caqui', 'Gelato', true, true, false, 'kg'),
('Caramelo Salgado', 'Gelato', true, true, false, 'kg'),
('Castanha do Pará', 'Gelato', true, true, false, 'kg'),
('Cheesecake de Framboesa', 'Gelato', true, true, false, 'kg'),
('Cheesecake de Frutas Vermelhas', 'Gelato', true, true, false, 'kg'),
('Cheseecake de Amora', 'Gelato', true, true, false, 'kg'),
('Choco Malte', 'Gelato', true, true, false, 'kg'),
('Chocolate Branco com Nutella', 'Gelato', true, true, false, 'kg'),
('Chocolate com Avelã', 'Gelato', true, true, false, 'kg'),
('Chocolate Supreme', 'Gelato', true, true, false, 'kg'),
('Chocolate Turco', 'Gelato', true, true, false, 'kg'),
('Cocada', 'Gelato', true, true, false, 'kg'),
('Coco', 'Gelato', true, true, false, 'kg'),
('Creme Brulèe', 'Gelato', true, true, false, 'kg'),
('Cupuaçu', 'Gelato', true, true, false, 'kg'),
('Danoninho', 'Gelato', true, true, false, 'kg'),
('Doce de Leite', 'Gelato', true, true, false, 'kg'),
('Dolce Mocha', 'Gelato', true, true, false, 'kg'),
('Don Vitto', 'Gelato', true, true, false, 'kg'),
('Frutas Vermelhas', 'Gelato', true, true, false, 'kg'),
('Gengibre', 'Gelato', true, true, false, 'kg'),
('Hortelã com Chocolate', 'Gelato', true, true, false, 'kg'),
('Iogurte com Amarena', 'Gelato', true, true, false, 'kg'),
('Iogurte Grego', 'Gelato', true, true, false, 'kg'),
('Jabuticaba', 'Gelato', true, true, false, 'kg'),
('Kinder', 'Gelato', true, true, false, 'kg'),
('Leite Condensado com Morango', 'Gelato', true, true, false, 'kg'),
('Leite Ninho com Nutella', 'Gelato', true, true, false, 'kg'),
('Lemon Pie', 'Gelato', true, true, false, 'kg'),
('Limão Rosa', 'Gelato', true, true, false, 'kg'),
('Limão Siciliano', 'Gelato', true, true, false, 'kg'),
('Limão Tahiti', 'Gelato', true, true, false, 'kg'),
('Macadâmia', 'Gelato', true, true, false, 'kg'),
('Manga', 'Gelato', true, true, false, 'kg'),
('Manjericão', 'Gelato', true, true, false, 'kg'),
('Maracujá', 'Gelato', true, true, false, 'kg'),
('Melancia', 'Gelato', true, true, false, 'kg'),
('Melão', 'Gelato', true, true, false, 'kg'),
('Milho Verde', 'Gelato', true, true, false, 'kg'),
('Mocha', 'Gelato', true, true, false, 'kg'),
('Morango', 'Gelato', true, true, false, 'kg'),
('Morango ao Leite c/ Stracciatella', 'Gelato', true, true, false, 'kg'),
('Nozes c/ Doce de Leite', 'Gelato', true, true, false, 'kg'),
('Paçoca com Chocolate', 'Gelato', true, true, false, 'kg'),
('Paçoquinha', 'Gelato', true, true, false, 'kg'),
('Pannacotta', 'Gelato', true, true, false, 'kg'),
('Pera', 'Gelato', true, true, false, 'kg'),
('Pêssego', 'Gelato', true, true, false, 'kg'),
('Pistache', 'Gelato', true, true, false, 'kg'),
('Prestígio', 'Gelato', true, true, false, 'kg'),
('Romeu e Julieta', 'Gelato', true, true, false, 'kg'),
('Sete Belo', 'Gelato', true, true, false, 'kg'),
('Sorvete Dog', 'Gelato', true, true, false, 'kg'),
('Tangerina', 'Gelato', true, true, false, 'kg'),
('Torta Belga', 'Gelato', true, true, false, 'kg'),
('Torta de Laranja', 'Gelato', true, true, false, 'kg'),
('Uva', 'Gelato', true, true, false, 'kg'),
('Iogurte com Maracujá', 'Gelato', true, true, false, 'kg'),
('Iogurte com Laranja', 'Gelato', true, true, false, 'kg'),
('Banana Nevada', 'Gelato', true, true, false, 'kg'),
('Chocolate Branco com Maracujá', 'Gelato', true, true, false, 'kg');
