-- SQL script to create the 'conciliacao_vendas' table for sales reconciliation
CREATE TABLE IF NOT EXISTS public.conciliacao_vendas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    date date NOT NULL,
    store text NOT NULL, -- 'ahu', 'altoxv'
    status text DEFAULT 'Aberto'::text, -- 'Aberto', 'Fechado'
    
    -- CAIXA DINHEIRO
    caixa_abertura numeric(10,2) DEFAULT 0.00 NOT NULL,
    caixa_vendas numeric(10,2) DEFAULT 0.00 NOT NULL,
    caixa_ajustes numeric(10,2) DEFAULT 0.00 NOT NULL,
    caixa_calculado numeric(10,2) DEFAULT 0.00 NOT NULL,
    caixa_informado numeric(10,2) DEFAULT 0.00 NOT NULL,
    caixa_real numeric(10,2) DEFAULT 0.00 NOT NULL,
    
    -- VENDAS PIX
    pix_calculado numeric(10,2) DEFAULT 0.00 NOT NULL,
    pix_realizado numeric(10,2) DEFAULT 0.00 NOT NULL,
    
    -- VENDAS CARTÃO
    cartao_calculado numeric(10,2) DEFAULT 0.00 NOT NULL,
    cartao_realizado numeric(10,2) DEFAULT 0.00 NOT NULL,
    
    -- VENDAS IFOOD
    ifood_calculado numeric(10,2) DEFAULT 0.00 NOT NULL,
    ifood_realizado numeric(10,2) DEFAULT 0.00 NOT NULL,
    
    -- Prevent duplicate records for the same store and date
    CONSTRAINT unique_store_date UNIQUE (store, date)
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.conciliacao_vendas ENABLE ROW LEVEL SECURITY;

-- Create policies for authenticated access (select, insert, update, delete)
CREATE POLICY "Allow read access to authenticated users" ON public.conciliacao_vendas
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow insert access to authenticated users" ON public.conciliacao_vendas
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Allow update access to authenticated users" ON public.conciliacao_vendas
    FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Allow delete access to authenticated users" ON public.conciliacao_vendas
    FOR DELETE TO authenticated USING (true);
