-- Script SQL para criar a tabela de frequência no Supabase e configurar RLS (Row Level Security)
-- Execute este código no SQL Editor do painel do seu Supabase para criar/atualizar a tabela e resolver o erro 403 Forbidden.

CREATE TABLE IF NOT EXISTS public.frequencia (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    date date NOT NULL,
    status text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT unique_employee_date UNIQUE (employee_id, date)
);

-- Conceder permissões para os roles públicos e autenticados
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON TABLE public.frequencia TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON TABLE public.frequencia TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON TABLE public.frequencia TO service_role;

-- =========================================================================
-- OPÇÃO 1 (Recomendada): Desativar RLS para esta tabela (Igual às tabelas Checklist e Vales)
-- =========================================================================
ALTER TABLE public.frequencia DISABLE ROW LEVEL SECURITY;

-- =========================================================================
-- OPÇÃO 2: Se preferir manter RLS ativado, execute as políticas de acesso abaixo:
-- =========================================================================
/*
ALTER TABLE public.frequencia ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read frequencia" ON public.frequencia;
CREATE POLICY "Allow read frequencia" ON public.frequencia FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow insert frequencia" ON public.frequencia;
CREATE POLICY "Allow insert frequencia" ON public.frequencia FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow update frequencia" ON public.frequencia;
CREATE POLICY "Allow update frequencia" ON public.frequencia FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow delete frequencia" ON public.frequencia;
CREATE POLICY "Allow delete frequencia" ON public.frequencia FOR DELETE TO anon, authenticated USING (true);
*/
