-- Script SQL para criar a tabela de histórico do colaborador no Supabase
-- Execute este código no SQL Editor do painel do seu Supabase:

CREATE TABLE IF NOT EXISTS public.historico_colaborador (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    type text NOT NULL,
    date date NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Conceder permissões para os roles públicos e autenticados
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON TABLE public.historico_colaborador TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON TABLE public.historico_colaborador TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON TABLE public.historico_colaborador TO service_role;

-- Desativar RLS para esta tabela operacional administrativa
ALTER TABLE public.historico_colaborador DISABLE ROW LEVEL SECURITY;
