UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Abacate';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Abacaxi com Hortelã';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Avelâ';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Banana Água';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Banoffe';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Baunilha';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Caqui';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Caramelo Salgado';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Castanha do Pará';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Cheesecake de Framboesa';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Cheesecake de Frutas Vermelhas';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Cheseecake de Amora';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Choco Malte';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Chocolate';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Chocolate Branco com Nutella';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Chocolate com Avelã';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Chocolate Supreme';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Chocolate Turco';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Cocada';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Coco';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Creme Brulèe';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Cupuaçu';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Danoninho';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Doce de Leite';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Dolce Mocha';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Don Vitto';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Frutas Vermelhas';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Gengibre';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Hortelã com Chocolate';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Iogurte com Amarena';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Iogurte Grego';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Jabuticaba';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Kinder';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Leite Condensado com Morango';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Leite Ninho com Nutella';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Lemon Pie';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Limão Rosa';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Limão Siciliano';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Limão Tahiti';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Macadâmia';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Manga';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Manjericão';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Maracujá';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Melancia';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Melão';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Milho Verde';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Mocha';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Morango';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Morango ao Leite c/ Stracciatella';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Nozes c/ Doce de Leite';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Paçoca com Chocolate';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Paçoquinha';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Pannacotta';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Pera';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Pêssego';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Pistache';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Prestígio';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Romeu e Julieta';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Sete Belo';
UPDATE cadastro_produtos SET tipo_gelato = 'Dog' WHERE TRIM(nome) = 'Sorvete Dog';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Stracciatella';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Tangerina';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Torta Belga';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Torta de Laranja';
UPDATE cadastro_produtos SET tipo_gelato = 'Fruta' WHERE TRIM(nome) = 'Uva';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Iogurte com Maracujá';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) IN ('Iogurte com Laranha', 'Iogurte com Laranja');
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Banana Nevada';
UPDATE cadastro_produtos SET tipo_gelato = 'Nata' WHERE TRIM(nome) = 'Chocolate Branco com Maracujá';
