


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_cron" WITH SCHEMA "pg_catalog";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "public";






CREATE EXTENSION IF NOT EXISTS "pgsodium";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."audit_log_trigger"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
DECLARE
    uid UUID;
BEGIN
    -- Tenta pegar o ID do usuário autenticado chamando a requisição do Supabase
    uid := auth.uid();
    
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO public.audit_logs (tabela_afetada, acao, dados_antigos, usuario_id)
        VALUES (TG_TABLE_NAME::TEXT, TG_OP, row_to_json(OLD)::JSONB, uid);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO public.audit_logs (tabela_afetada, acao, dados_antigos, dados_novos, usuario_id)
        VALUES (TG_TABLE_NAME::TEXT, TG_OP, row_to_json(OLD)::JSONB, row_to_json(NEW)::JSONB, uid);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO public.audit_logs (tabela_afetada, acao, dados_novos, usuario_id)
        VALUES (TG_TABLE_NAME::TEXT, TG_OP, row_to_json(NEW)::JSONB, uid);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$;


ALTER FUNCTION "public"."audit_log_trigger"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_deleted_profile"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  -- Apaga o usuário da tabela de autenticação (auth.users) que tenha o mesmo ID
  DELETE FROM auth.users WHERE id = old.id;
  RETURN old;
END;
$$;


ALTER FUNCTION "public"."handle_deleted_profile"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1))
  );
  RETURN new;
END;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_total_vales"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  -- Atualizar para o NOVO registro (INSERT ou UPDATE)
  IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') THEN
    UPDATE profiles
    SET total_vales = (
      SELECT COALESCE(SUM(
        CASE WHEN "Item" = 'Crédito (Acréscimo)' THEN "valor" ELSE -"valor" END
      ), 0)
      FROM "Vales"
      WHERE "Nome" = NEW."Nome"
    )
    WHERE name = NEW."Nome";
  END IF;

  -- Atualizar para o registro ANTIGO (DELETE ou UPDATE de nome)
  IF (TG_OP = 'DELETE' OR TG_OP = 'UPDATE') THEN
    UPDATE profiles
    SET total_vales = (
      SELECT COALESCE(SUM(
        CASE WHEN "Item" = 'Crédito (Acréscimo)' THEN "valor" ELSE -"valor" END
      ), 0)
      FROM "Vales"
      WHERE "Nome" = OLD."Nome"
    )
    WHERE name = OLD."Nome";
  END IF;

  RETURN NULL;
END;
$$;


ALTER FUNCTION "public"."update_total_vales"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_user_password"("target_user_id" "uuid", "new_password" "text") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  -- Criptografa a nova senha e atualiza no registro do usuário específico
  UPDATE auth.users
  SET encrypted_password = crypt(new_password, gen_salt('bf')),
      updated_at = now()
  WHERE id = target_user_id;
END;
$$;


ALTER FUNCTION "public"."update_user_password"("target_user_id" "uuid", "new_password" "text") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Checklist" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "checklist" "text",
    "person" "text",
    "store" "text",
    "massas" "text",
    "brownies" "text",
    "panos" "text",
    "money_data" "jsonb"
);


ALTER TABLE "public"."Checklist" OWNER TO "postgres";


ALTER TABLE "public"."Checklist" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Checklist_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Vales" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "Nome" "text",
    "Unidade" "text",
    "Item" "text",
    "valor" numeric
);


ALTER TABLE "public"."Vales" OWNER TO "postgres";


ALTER TABLE "public"."Vales" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Vales_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Vouchers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "voucher_id" "text",
    "active" boolean DEFAULT true,
    "date_consumed" timestamp without time zone,
    "store_consumed" "text",
    "person_consumed" "text",
    "value" "text"
);


ALTER TABLE "public"."Vouchers" OWNER TO "postgres";


ALTER TABLE "public"."Vouchers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Vouchers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."afericao_porcao" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "unit" "text" NOT NULL,
    "employee_name" "text" NOT NULL,
    "cup_number" integer NOT NULL,
    "portion_label" "text",
    "weight_grams" numeric NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."afericao_porcao" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."audit_logs" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "tabela_afetada" "text" NOT NULL,
    "acao" "text" NOT NULL,
    "dados_antigos" "jsonb",
    "dados_novos" "jsonb",
    "usuario_id" "uuid",
    "data_hora" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "audit_logs_acao_check" CHECK (("acao" = ANY (ARRAY['INSERT'::"text", 'UPDATE'::"text", 'DELETE'::"text"])))
);


ALTER TABLE "public"."audit_logs" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."cadastro_insumos" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "nome" "text" NOT NULL,
    "nome_simples_unitario" "text",
    "tipo" "text",
    "fornecedor_padrao" "text",
    "quantidade_conversao" numeric,
    "unidade_conversao" "text",
    "custo_considerado" numeric,
    "ativo" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "config_estoque" "jsonb" DEFAULT '{}'::"jsonb",
    "ordem" integer DEFAULT 0,
    "custo_considerado_unitario" numeric,
    "fator_desperdicio" numeric DEFAULT 0,
    "inventario_especial" boolean DEFAULT false,
    "unidade_estoque" "text",
    "unidade_consumo" "text"
);


ALTER TABLE "public"."cadastro_insumos" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."cadastro_produtos" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "nome" "text" NOT NULL,
    "categoria" "text",
    "ativo" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "preco_venda" numeric,
    "unidade_venda" character varying(50),
    "ordem" integer DEFAULT 0,
    "metodo_preparo" "text",
    "is_sabor" boolean DEFAULT false,
    "is_preparacao" boolean DEFAULT false,
    "codigo" "text",
    "rendimento" numeric DEFAULT 1,
    "preco_venda_food_service" numeric,
    "tipo_gelato" "text"
);


ALTER TABLE "public"."cadastro_produtos" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."caixa_dinheiro_lancamentos" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "data" "date" NOT NULL,
    "descricao" "text" NOT NULL,
    "tipo" "text" NOT NULL,
    "valores_json" "jsonb" NOT NULL,
    "valor_total" numeric NOT NULL,
    "user_id" "uuid",
    CONSTRAINT "caixa_dinheiro_lancamentos_tipo_check" CHECK (("tipo" = ANY (ARRAY['entrada'::"text", 'saida'::"text"])))
);


ALTER TABLE "public"."caixa_dinheiro_lancamentos" OWNER TO "postgres";


ALTER TABLE "public"."caixa_dinheiro_lancamentos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."caixa_dinheiro_lancamentos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."cardsahu" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "title" "text" NOT NULL,
    "status" "text" NOT NULL,
    "production_date" "date" NOT NULL,
    "entry_date" "date",
    "created_by" "text" DEFAULT 'A definir'::"text" NOT NULL,
    "last_edited_by" "text" DEFAULT 'A definir'::"text" NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "exit_date" "date",
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "history" "jsonb" DEFAULT '[]'::"jsonb",
    CONSTRAINT "cards_status_check" CHECK (("status" = ANY (ARRAY['quebras'::"text", 'freezer-estoque'::"text", 'vitrine-atual'::"text", 'cubas-saidas-vitrine'::"text", 'excluidos'::"text"])))
);


ALTER TABLE "public"."cardsahu" OWNER TO "postgres";


COMMENT ON TABLE "public"."cardsahu" IS 'This is a duplicate of cardsaltoxv';



CREATE TABLE IF NOT EXISTS "public"."cardsaltoxv" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "title" "text" NOT NULL,
    "status" "text" NOT NULL,
    "production_date" "date" NOT NULL,
    "entry_date" "date",
    "created_by" "text" DEFAULT 'A definir'::"text" NOT NULL,
    "last_edited_by" "text" DEFAULT 'A definir'::"text" NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "exit_date" "date",
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "history" "jsonb" DEFAULT '[]'::"jsonb",
    CONSTRAINT "cards_status_check" CHECK (("status" = ANY (ARRAY['quebras'::"text", 'freezer-estoque'::"text", 'vitrine-atual'::"text", 'cubas-saidas-vitrine'::"text", 'excluidos'::"text"])))
);


ALTER TABLE "public"."cardsaltoxv" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."categorias_financeiras" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "nome" "text" NOT NULL,
    "parent_id" "uuid",
    "ativo" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."categorias_financeiras" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."clientes_food_service" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "nome" "text" NOT NULL,
    "email" "text",
    "telefone" "text",
    "cpf_cnpj" "text",
    "endereco" "text",
    "observacoes" "text",
    "ativo" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "status" "text" DEFAULT 'Lead'::"text",
    "cep" "text",
    "latitude" numeric,
    "longitude" numeric,
    "tipo" "text" DEFAULT 'Restaurante'::"text",
    "nome_contato" "text",
    "data_primeiro_contato" "date",
    "data_ultimo_contato" "date",
    "data_proximo_contato" "date"
);


ALTER TABLE "public"."clientes_food_service" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."contas" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "banco" "text" NOT NULL,
    "agencia" "text",
    "conta_corrente" "text",
    "data_inicial" "date",
    "saldo_inicial" numeric DEFAULT 0,
    "cnpj" "text",
    "descricao" "text",
    "ativo" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."contas" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."contas_fixas" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "descricao" "text" NOT NULL,
    "valor" numeric NOT NULL,
    "dia_vencimento" integer NOT NULL,
    "fornecedor_cliente" "text",
    "categoria" "text",
    "user_id" "uuid",
    "ativo" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."contas_fixas" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."contas_pagar_receber" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "descricao" "text" NOT NULL,
    "data" "date" NOT NULL,
    "valor" numeric NOT NULL,
    "fornecedor_cliente" "text",
    "categoria" "text",
    "user_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "updated_at" timestamp with time zone,
    "status_revisao" "text"
);


ALTER TABLE "public"."contas_pagar_receber" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."entradas_mercadoria" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "insumo_id" "uuid",
    "data_compra" "date" NOT NULL,
    "fornecedor" "text",
    "quantidade_comprada" numeric NOT NULL,
    "valor_unitario" numeric NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "user_id" "uuid",
    "status_revisao" character varying(20) DEFAULT 'none'::character varying,
    "revisao_observacao" "text",
    "updated_at" timestamp with time zone
);


ALTER TABLE "public"."entradas_mercadoria" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."feriados_globais" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "date" "date" NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."feriados_globais" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."feriados_trabalhados" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "employee_id" "uuid" NOT NULL,
    "data_feriado" "date" NOT NULL,
    "nome_feriado" "text" NOT NULL,
    "data_folga" "date",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "pago_em_dobro" boolean DEFAULT false
);


ALTER TABLE "public"."feriados_trabalhados" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."ficha_tecnica" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "produto_id" "uuid",
    "insumo_id" "uuid",
    "quantidade" numeric NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "produto_base_id" "uuid",
    "subgrupo" "text"
);


ALTER TABLE "public"."ficha_tecnica" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."fornecedores" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "ativo" boolean DEFAULT true,
    "nome" "text" NOT NULL,
    "razao_social" "text",
    "metodo_compra" "text",
    "email" "text",
    "telefone" "text",
    "contato_nome" "text",
    "cnpj" "text",
    "observacoes" "text"
);


ALTER TABLE "public"."fornecedores" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."frequencia" (
    "id" bigint NOT NULL,
    "employee_id" "uuid" NOT NULL,
    "date" "date" NOT NULL,
    "status" "text" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "observacao" "text",
    "observacao_by" "uuid",
    "observacao_at" timestamp with time zone
);


ALTER TABLE "public"."frequencia" OWNER TO "postgres";


ALTER TABLE "public"."frequencia" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."frequencia_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."historico_colaborador" (
    "id" bigint NOT NULL,
    "employee_id" "uuid" NOT NULL,
    "created_by" "uuid",
    "type" "text" NOT NULL,
    "date" "date" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."historico_colaborador" OWNER TO "postgres";


ALTER TABLE "public"."historico_colaborador" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."historico_colaborador_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."historico_crm" (
    "id" bigint NOT NULL,
    "cliente_id" "uuid" NOT NULL,
    "created_by" "uuid",
    "type" "text" NOT NULL,
    "date" "date" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."historico_crm" OWNER TO "postgres";


ALTER TABLE "public"."historico_crm" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."historico_crm_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."historico_pagamentos_vt_vr" (
    "id" integer NOT NULL,
    "employee_id" "uuid",
    "mes_referencia" integer NOT NULL,
    "ano_referencia" integer NOT NULL,
    "valor_vt" numeric(10,2) DEFAULT 0,
    "valor_vr" numeric(10,2) DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "data_pagamento" "date",
    "dias_previstos" integer,
    "dias_desconto" integer
);


ALTER TABLE "public"."historico_pagamentos_vt_vr" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."historico_pagamentos_vt_vr_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."historico_pagamentos_vt_vr_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."historico_pagamentos_vt_vr_id_seq" OWNED BY "public"."historico_pagamentos_vt_vr"."id";



CREATE TABLE IF NOT EXISTS "public"."inventario_insumos" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "insumo_id" "uuid",
    "data_inventario" "date" NOT NULL,
    "unidade" "text" NOT NULL,
    "quantidade" numeric NOT NULL,
    "user_id" "uuid",
    "updated_at" timestamp with time zone
);


ALTER TABLE "public"."inventario_insumos" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."lancamentos_financeiros" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "data" "date" NOT NULL,
    "descricao" "text" NOT NULL,
    "valor" numeric NOT NULL,
    "fornecedor" "text",
    "categoria" "text",
    "conta" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "status_revisao" "text",
    "revisao_observacao" "text",
    "updated_at" timestamp with time zone
);


ALTER TABLE "public"."lancamentos_financeiros" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."lista_compras_manual" (
    "id" integer NOT NULL,
    "insumo_id" "uuid",
    "quantidade" numeric DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "comprado" boolean DEFAULT false
);


ALTER TABLE "public"."lista_compras_manual" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."lista_compras_manual_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."lista_compras_manual_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."lista_compras_manual_id_seq" OWNED BY "public"."lista_compras_manual"."id";



CREATE TABLE IF NOT EXISTS "public"."movimentacoes_estoque" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "insumo_id" "uuid",
    "data_movimentacao" "date" NOT NULL,
    "quantidade" numeric NOT NULL,
    "origem" "text" NOT NULL,
    "destino" "text" NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "status_revisao" character varying(20) DEFAULT 'none'::character varying,
    "revisao_observacao" "text",
    "updated_at" timestamp with time zone
);


ALTER TABLE "public"."movimentacoes_estoque" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."notificacao_lojas" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "titulo" "text" NOT NULL,
    "mensagem" "text" NOT NULL,
    "loja" "text" DEFAULT 'Todas'::"text",
    "data_agendada" timestamp with time zone,
    "repeticao_diaria" boolean DEFAULT false,
    "dias_semana" "jsonb" DEFAULT '[]'::"jsonb"
);


ALTER TABLE "public"."notificacao_lojas" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."ordem_producao" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "produto_id" "uuid" NOT NULL,
    "data_ordem" "date" NOT NULL,
    "quantidade" numeric NOT NULL,
    "user_id" "uuid",
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "data_producao" "date",
    "peso_bruto" numeric,
    "tara" numeric,
    "codigo" "text"
);


ALTER TABLE "public"."ordem_producao" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."pedidos_food_service" (
    "id" bigint NOT NULL,
    "produto_id" "uuid",
    "data_pedido" "date" NOT NULL,
    "cliente" "text",
    "quantidade" numeric NOT NULL,
    "valor_unitario" numeric,
    "user_id" "uuid",
    "status_revisao" "text",
    "revisao_observacao" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "quantidade_produzida" numeric,
    "data_entrega" "date"
);


ALTER TABLE "public"."pedidos_food_service" OWNER TO "postgres";


ALTER TABLE "public"."pedidos_food_service" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pedidos_food_service_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."producao_realizada" (
    "id" integer NOT NULL,
    "produto_id" "uuid",
    "data_producao" "date" NOT NULL,
    "user_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "codigo" "text",
    "peso_bruto" numeric,
    "tara" numeric,
    "peso_liquido" numeric,
    "data_entrada" "date",
    "destino" "text",
    "validade" "date",
    "status_revisao" character varying(20) DEFAULT 'none'::character varying,
    "revisao_observacao" "text"
);


ALTER TABLE "public"."producao_realizada" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."producao_realizada_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."producao_realizada_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."producao_realizada_id_seq" OWNED BY "public"."producao_realizada"."id";



CREATE TABLE IF NOT EXISTS "public"."produtos_vale" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "nome" character varying(255) NOT NULL,
    "valor" numeric(10,2) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."produtos_vale" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "email" "text" NOT NULL,
    "name" "text" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "short_id" "text",
    "is_admin" boolean DEFAULT false,
    "controlar_frequencia" boolean DEFAULT true,
    "folgas_fixas" "text" DEFAULT ''::"text",
    "ativo" boolean DEFAULT true,
    "data_registro" "date",
    "passagens_urbs" integer DEFAULT 0,
    "passagens_metrocard" integer DEFAULT 0,
    "data_demissao" "date",
    "cpf" "text",
    "rg" "text",
    "cargo" "text",
    "telefone" "text",
    "endereco" "text",
    "sexo" "text",
    "data_nascimento" "date",
    "cidade_nascimento" "text",
    "estado_civil" "text",
    "dependentes" integer,
    "ctps" "text",
    "unidade_registrada" "text",
    "chaves" integer,
    "uniformes" integer,
    "total_vales" numeric DEFAULT 0,
    "rules_confirmed_at" timestamp with time zone
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."salgados_inventory" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "unit" "text" NOT NULL,
    "collection" "text" NOT NULL,
    "item_name" "text" NOT NULL,
    "quantity" integer DEFAULT 0 NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."salgados_inventory" OWNER TO "postgres";


ALTER TABLE ONLY "public"."historico_pagamentos_vt_vr" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."historico_pagamentos_vt_vr_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."lista_compras_manual" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."lista_compras_manual_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."producao_realizada" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."producao_realizada_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."Checklist"
    ADD CONSTRAINT "Checklist_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Vales"
    ADD CONSTRAINT "Vales_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Vouchers"
    ADD CONSTRAINT "Vouchers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."afericao_porcao"
    ADD CONSTRAINT "afericao_porcao_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."audit_logs"
    ADD CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."cadastro_insumos"
    ADD CONSTRAINT "cadastro_insumos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."cadastro_produtos"
    ADD CONSTRAINT "cadastro_produtos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."caixa_dinheiro_lancamentos"
    ADD CONSTRAINT "caixa_dinheiro_lancamentos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."cardsaltoxv"
    ADD CONSTRAINT "cards_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."cardsahu"
    ADD CONSTRAINT "cardsahu_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."categorias_financeiras"
    ADD CONSTRAINT "categorias_financeiras_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."clientes_food_service"
    ADD CONSTRAINT "clientes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."contas_fixas"
    ADD CONSTRAINT "contas_fixas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."contas_pagar_receber"
    ADD CONSTRAINT "contas_pagar_receber_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."contas"
    ADD CONSTRAINT "contas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."entradas_mercadoria"
    ADD CONSTRAINT "entradas_mercadoria_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."feriados_globais"
    ADD CONSTRAINT "feriados_globais_date_key" UNIQUE ("date");



ALTER TABLE ONLY "public"."feriados_globais"
    ADD CONSTRAINT "feriados_globais_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."feriados_trabalhados"
    ADD CONSTRAINT "feriados_trabalhados_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ficha_tecnica"
    ADD CONSTRAINT "ficha_tecnica_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."fornecedores"
    ADD CONSTRAINT "fornecedores_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."frequencia"
    ADD CONSTRAINT "frequencia_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."historico_colaborador"
    ADD CONSTRAINT "historico_colaborador_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."historico_crm"
    ADD CONSTRAINT "historico_crm_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."historico_pagamentos_vt_vr"
    ADD CONSTRAINT "historico_pagamentos_vt_vr_employee_id_mes_referencia_ano_r_key" UNIQUE ("employee_id", "mes_referencia", "ano_referencia");



ALTER TABLE ONLY "public"."historico_pagamentos_vt_vr"
    ADD CONSTRAINT "historico_pagamentos_vt_vr_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."inventario_insumos"
    ADD CONSTRAINT "inventario_insumos_insumo_id_unidade_data_inventario_key" UNIQUE ("insumo_id", "unidade", "data_inventario");



ALTER TABLE ONLY "public"."inventario_insumos"
    ADD CONSTRAINT "inventario_insumos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."lancamentos_financeiros"
    ADD CONSTRAINT "lancamentos_financeiros_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."lista_compras_manual"
    ADD CONSTRAINT "lista_compras_manual_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."movimentacoes_estoque"
    ADD CONSTRAINT "movimentacoes_estoque_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notificacao_lojas"
    ADD CONSTRAINT "notificacao_lojas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ordem_producao"
    ADD CONSTRAINT "ordem_producao_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pedidos_food_service"
    ADD CONSTRAINT "pedidos_food_service_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."producao_realizada"
    ADD CONSTRAINT "producao_realizada_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."produtos_vale"
    ADD CONSTRAINT "produtos_vale_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."salgados_inventory"
    ADD CONSTRAINT "salgados_inventory_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."frequencia"
    ADD CONSTRAINT "unique_employee_date" UNIQUE ("employee_id", "date");



CREATE UNIQUE INDEX "salgados_inventory_unit_collection_item_name_idx" ON "public"."salgados_inventory" USING "btree" ("unit", "collection", "item_name");



CREATE OR REPLACE TRIGGER "on_profile_deleted" AFTER DELETE ON "public"."profiles" FOR EACH ROW EXECUTE FUNCTION "public"."handle_deleted_profile"();



CREATE OR REPLACE TRIGGER "trg_audit_checklist" AFTER INSERT OR DELETE OR UPDATE ON "public"."Checklist" FOR EACH ROW EXECUTE FUNCTION "public"."audit_log_trigger"();



CREATE OR REPLACE TRIGGER "trg_audit_frequencia" AFTER INSERT OR DELETE OR UPDATE ON "public"."frequencia" FOR EACH ROW EXECUTE FUNCTION "public"."audit_log_trigger"();



CREATE OR REPLACE TRIGGER "trg_audit_historico_colaborador" AFTER INSERT OR DELETE OR UPDATE ON "public"."historico_colaborador" FOR EACH ROW EXECUTE FUNCTION "public"."audit_log_trigger"();



CREATE OR REPLACE TRIGGER "trg_audit_profiles" AFTER INSERT OR DELETE OR UPDATE ON "public"."profiles" FOR EACH ROW EXECUTE FUNCTION "public"."audit_log_trigger"();



CREATE OR REPLACE TRIGGER "trg_audit_vales" AFTER INSERT OR DELETE OR UPDATE ON "public"."Vales" FOR EACH ROW EXECUTE FUNCTION "public"."audit_log_trigger"();



CREATE OR REPLACE TRIGGER "trg_audit_vouchers" AFTER INSERT OR DELETE OR UPDATE ON "public"."Vouchers" FOR EACH ROW EXECUTE FUNCTION "public"."audit_log_trigger"();



CREATE OR REPLACE TRIGGER "trigger_update_total_vales" AFTER INSERT OR DELETE OR UPDATE ON "public"."Vales" FOR EACH ROW EXECUTE FUNCTION "public"."update_total_vales"();



ALTER TABLE ONLY "public"."audit_logs"
    ADD CONSTRAINT "audit_logs_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."caixa_dinheiro_lancamentos"
    ADD CONSTRAINT "caixa_dinheiro_lancamentos_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."categorias_financeiras"
    ADD CONSTRAINT "categorias_financeiras_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."categorias_financeiras"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."contas_fixas"
    ADD CONSTRAINT "contas_fixas_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."contas_pagar_receber"
    ADD CONSTRAINT "contas_pagar_receber_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."entradas_mercadoria"
    ADD CONSTRAINT "entradas_mercadoria_insumo_id_fkey" FOREIGN KEY ("insumo_id") REFERENCES "public"."cadastro_insumos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."feriados_trabalhados"
    ADD CONSTRAINT "feriados_trabalhados_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ficha_tecnica"
    ADD CONSTRAINT "ficha_tecnica_insumo_id_fkey" FOREIGN KEY ("insumo_id") REFERENCES "public"."cadastro_insumos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ficha_tecnica"
    ADD CONSTRAINT "ficha_tecnica_produto_base_id_fkey" FOREIGN KEY ("produto_base_id") REFERENCES "public"."cadastro_produtos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ficha_tecnica"
    ADD CONSTRAINT "ficha_tecnica_produto_id_fkey" FOREIGN KEY ("produto_id") REFERENCES "public"."cadastro_produtos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."entradas_mercadoria"
    ADD CONSTRAINT "fk_entradas_mercadoria_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."frequencia"
    ADD CONSTRAINT "frequencia_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."frequencia"
    ADD CONSTRAINT "frequencia_observacao_by_fkey" FOREIGN KEY ("observacao_by") REFERENCES "public"."profiles"("id");



ALTER TABLE ONLY "public"."historico_colaborador"
    ADD CONSTRAINT "historico_colaborador_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."historico_colaborador"
    ADD CONSTRAINT "historico_colaborador_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."historico_crm"
    ADD CONSTRAINT "historico_crm_cliente_id_fkey" FOREIGN KEY ("cliente_id") REFERENCES "public"."clientes_food_service"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."historico_crm"
    ADD CONSTRAINT "historico_crm_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."historico_pagamentos_vt_vr"
    ADD CONSTRAINT "historico_pagamentos_vt_vr_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."inventario_insumos"
    ADD CONSTRAINT "inventario_insumos_insumo_id_fkey" FOREIGN KEY ("insumo_id") REFERENCES "public"."cadastro_insumos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."inventario_insumos"
    ADD CONSTRAINT "inventario_insumos_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id");



ALTER TABLE ONLY "public"."lancamentos_financeiros"
    ADD CONSTRAINT "lancamentos_financeiros_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."lista_compras_manual"
    ADD CONSTRAINT "lista_compras_manual_insumo_id_fkey" FOREIGN KEY ("insumo_id") REFERENCES "public"."cadastro_insumos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."movimentacoes_estoque"
    ADD CONSTRAINT "movimentacoes_estoque_insumo_id_fkey" FOREIGN KEY ("insumo_id") REFERENCES "public"."cadastro_insumos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."movimentacoes_estoque"
    ADD CONSTRAINT "movimentacoes_estoque_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id");



ALTER TABLE ONLY "public"."ordem_producao"
    ADD CONSTRAINT "ordem_producao_produto_id_fkey" FOREIGN KEY ("produto_id") REFERENCES "public"."cadastro_produtos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ordem_producao"
    ADD CONSTRAINT "ordem_producao_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."pedidos_food_service"
    ADD CONSTRAINT "pedidos_food_service_produto_id_fkey" FOREIGN KEY ("produto_id") REFERENCES "public"."cadastro_produtos"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."pedidos_food_service"
    ADD CONSTRAINT "pedidos_food_service_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."producao_realizada"
    ADD CONSTRAINT "producao_realizada_produto_id_fkey" FOREIGN KEY ("produto_id") REFERENCES "public"."cadastro_produtos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."producao_realizada"
    ADD CONSTRAINT "producao_realizada_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Admins podem fazer tudo em feriados_globais" ON "public"."feriados_globais" USING ((EXISTS ( SELECT 1
   FROM "public"."profiles"
  WHERE (("profiles"."id" = "auth"."uid"()) AND ("profiles"."is_admin" = true)))));



CREATE POLICY "Admins podem fazer tudo em feriados_trabalhados" ON "public"."feriados_trabalhados" USING ((EXISTS ( SELECT 1
   FROM "public"."profiles"
  WHERE (("profiles"."id" = "auth"."uid"()) AND ("profiles"."is_admin" = true)))));



CREATE POLICY "Allow Delete Cards" ON "public"."cardsahu" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Allow Delete Cards" ON "public"."cardsaltoxv" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Allow delete frequencia" ON "public"."frequencia" FOR DELETE TO "authenticated", "anon" USING (true);



CREATE POLICY "Allow delete historico_colaborador" ON "public"."historico_colaborador" FOR DELETE TO "authenticated", "anon" USING (true);



CREATE POLICY "Allow insert cards" ON "public"."cardsahu" FOR INSERT TO "authenticated", "anon" WITH CHECK (true);



CREATE POLICY "Allow insert cards" ON "public"."cardsaltoxv" FOR INSERT TO "authenticated", "anon" WITH CHECK (true);



CREATE POLICY "Allow insert frequencia" ON "public"."frequencia" FOR INSERT TO "authenticated", "anon" WITH CHECK (true);



CREATE POLICY "Allow insert historico_colaborador" ON "public"."historico_colaborador" FOR INSERT TO "authenticated", "anon" WITH CHECK (true);



CREATE POLICY "Allow read access to profiles for all authenticated users" ON "public"."profiles" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Allow read cards" ON "public"."cardsahu" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Allow read cards" ON "public"."cardsaltoxv" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Allow read frequencia" ON "public"."frequencia" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Allow read historico_colaborador" ON "public"."historico_colaborador" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Allow update access to own profile" ON "public"."profiles" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "id"));



CREATE POLICY "Allow update cards" ON "public"."cardsahu" FOR UPDATE TO "authenticated", "anon" USING (true) WITH CHECK (true);



CREATE POLICY "Allow update cards" ON "public"."cardsaltoxv" FOR UPDATE TO "authenticated", "anon" USING (true) WITH CHECK (true);



CREATE POLICY "Allow update frequencia" ON "public"."frequencia" FOR UPDATE TO "authenticated", "anon" USING (true) WITH CHECK (true);



CREATE POLICY "Allow update historico_colaborador" ON "public"."historico_colaborador" FOR UPDATE TO "authenticated", "anon" USING (true) WITH CHECK (true);



CREATE POLICY "Enable ALL for authenticated users" ON "public"."contas_pagar_receber" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Enable all for authenticated users" ON "public"."contas_fixas" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Enable delete access for all authenticated users" ON "public"."fornecedores" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Enable delete for authenticated users" ON "public"."lancamentos_financeiros" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Enable delete for authenticated users" ON "public"."ordem_producao" FOR DELETE USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable delete for authenticated users only" ON "public"."clientes_food_service" FOR DELETE USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable insert access for all authenticated users" ON "public"."fornecedores" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users" ON "public"."lancamentos_financeiros" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users" ON "public"."ordem_producao" FOR INSERT WITH CHECK (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable insert for authenticated users only" ON "public"."clientes_food_service" FOR INSERT WITH CHECK (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable read access for all authenticated users" ON "public"."fornecedores" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Enable read access for all authenticated users" ON "public"."lancamentos_financeiros" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Enable read access for all authenticated users" ON "public"."ordem_producao" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable read access for all users" ON "public"."Vouchers" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."clientes_food_service" FOR SELECT USING (true);



CREATE POLICY "Enable update access for all authenticated users" ON "public"."fornecedores" FOR UPDATE TO "authenticated" USING (true);



CREATE POLICY "Enable update for authenticated users" ON "public"."lancamentos_financeiros" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Enable update for authenticated users" ON "public"."ordem_producao" FOR UPDATE USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable update for authenticated users only" ON "public"."clientes_food_service" FOR UPDATE USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Permitir ALL em cadastro_produtos" ON "public"."cadastro_produtos" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Permitir ALL em ficha_tecnica" ON "public"."ficha_tecnica" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Permitir INSERT em notificacao_lojas" ON "public"."notificacao_lojas" FOR INSERT WITH CHECK (true);



CREATE POLICY "Permitir SELECT em cadastro_produtos" ON "public"."cadastro_produtos" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Permitir SELECT em ficha_tecnica" ON "public"."ficha_tecnica" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Permitir UPDATE em notificacao_lojas" ON "public"."notificacao_lojas" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "Permitir acesso total" ON "public"."entradas_mercadoria" USING (true) WITH CHECK (true);



CREATE POLICY "Permitir acesso total a usuários autenticados" ON "public"."cadastro_insumos" USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Permitir acesso total na lista_compras_manual" ON "public"."lista_compras_manual" USING (true) WITH CHECK (true);



CREATE POLICY "Permitir acesso total na producao_realizada" ON "public"."producao_realizada" USING (true) WITH CHECK (true);



CREATE POLICY "Permitir atualizacao para usuarios autenticados" ON "public"."inventario_insumos" FOR UPDATE TO "authenticated" USING (true);



CREATE POLICY "Permitir atualizacao para usuarios autenticados" ON "public"."movimentacoes_estoque" FOR UPDATE TO "authenticated" USING (true);



CREATE POLICY "Permitir atualização de vouchers para autenticados" ON "public"."Vouchers" FOR UPDATE TO "authenticated" USING (true);



CREATE POLICY "Permitir atualização em produtos_vale" ON "public"."produtos_vale" FOR UPDATE USING (true);



CREATE POLICY "Permitir atualização para autenticados" ON "public"."lancamentos_financeiros" FOR UPDATE TO "authenticated" USING (true);



CREATE POLICY "Permitir atualização para usuários autenticados" ON "public"."caixa_dinheiro_lancamentos" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Permitir atualização para usuários autenticados" ON "public"."categorias_financeiras" FOR UPDATE TO "authenticated" USING (true);



CREATE POLICY "Permitir atualização para usuários autenticados" ON "public"."contas" FOR UPDATE TO "authenticated" USING (true);



CREATE POLICY "Permitir criação de vouchers para autenticados" ON "public"."Vouchers" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Permitir deleção em produtos_vale" ON "public"."produtos_vale" FOR DELETE USING (true);



CREATE POLICY "Permitir edição (UPDATE) para todos os usuários autenticados" ON "public"."profiles" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Permitir edição para usuários logados" ON "public"."Vales" FOR UPDATE TO "authenticated" USING (true);



CREATE POLICY "Permitir exclusao para usuarios autenticados" ON "public"."inventario_insumos" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Permitir exclusao para usuarios autenticados" ON "public"."movimentacoes_estoque" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Permitir exclusão (DELETE) para todos os usuários autenticado" ON "public"."profiles" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Permitir exclusão de vouchers para autenticados" ON "public"."Vouchers" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Permitir exclusão para autenticados" ON "public"."lancamentos_financeiros" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Permitir exclusão para usuários autenticados" ON "public"."caixa_dinheiro_lancamentos" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Permitir exclusão para usuários autenticados" ON "public"."categorias_financeiras" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Permitir exclusão para usuários autenticados" ON "public"."contas" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Permitir exclusão para usuários logados" ON "public"."Vales" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Permitir insercao para usuarios autenticados" ON "public"."inventario_insumos" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Permitir insercao para usuarios autenticados" ON "public"."movimentacoes_estoque" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Permitir inserção (INSERT) para todos os usuários autenticad" ON "public"."profiles" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Permitir inserção e atualização" ON "public"."historico_pagamentos_vt_vr" USING (("auth"."role"() = 'authenticated'::"text")) WITH CHECK (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Permitir inserção em produtos_vale" ON "public"."produtos_vale" FOR INSERT WITH CHECK (true);



CREATE POLICY "Permitir inserção para autenticados" ON "public"."lancamentos_financeiros" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Permitir inserção para usuários autenticados" ON "public"."caixa_dinheiro_lancamentos" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Permitir inserção para usuários autenticados" ON "public"."categorias_financeiras" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Permitir inserção para usuários autenticados" ON "public"."contas" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Permitir inserção para usuários logados" ON "public"."Vales" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Permitir leitura (SELECT) para todos os usuários autenticados" ON "public"."profiles" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Permitir leitura de logs para usuarios autenticados" ON "public"."audit_logs" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Permitir leitura de produtos_vale" ON "public"."produtos_vale" FOR SELECT USING (true);



CREATE POLICY "Permitir leitura de vouchers para autenticados" ON "public"."Vouchers" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Permitir leitura para autenticados" ON "public"."lancamentos_financeiros" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Permitir leitura para logados" ON "public"."historico_pagamentos_vt_vr" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Permitir leitura para usuarios autenticados" ON "public"."inventario_insumos" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Permitir leitura para usuarios autenticados" ON "public"."movimentacoes_estoque" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Permitir leitura para usuários autenticados" ON "public"."caixa_dinheiro_lancamentos" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Permitir leitura para usuários autenticados" ON "public"."categorias_financeiras" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Permitir leitura para usuários autenticados" ON "public"."contas" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Permitir leitura para usuários logados" ON "public"."Vales" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Permitir leitura pública" ON "public"."notificacao_lojas" FOR SELECT USING (true);



CREATE POLICY "Permitir tudo no historico_crm" ON "public"."historico_crm" USING (true);



CREATE POLICY "Permitir tudo para admin" ON "public"."notificacao_lojas" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Permitir tudo para usuários autenticados" ON "public"."pedidos_food_service" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Todos podem visualizar feriados_globais" ON "public"."feriados_globais" FOR SELECT USING (true);



CREATE POLICY "Usuários podem ver seus próprios feriados trabalhados" ON "public"."feriados_trabalhados" FOR SELECT USING (("auth"."uid"() = "employee_id"));



ALTER TABLE "public"."Vales" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Vouchers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."audit_logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."cadastro_insumos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."cadastro_produtos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."caixa_dinheiro_lancamentos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."cardsahu" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."cardsaltoxv" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."categorias_financeiras" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."clientes_food_service" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."contas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."contas_fixas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."contas_pagar_receber" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."entradas_mercadoria" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."feriados_globais" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."feriados_trabalhados" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ficha_tecnica" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."fornecedores" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."frequencia" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."historico_colaborador" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."historico_crm" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."historico_pagamentos_vt_vr" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."inventario_insumos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."lancamentos_financeiros" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."lista_compras_manual" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."movimentacoes_estoque" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."notificacao_lojas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ordem_producao" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pedidos_food_service" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."producao_realizada" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."produtos_vale" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."caixa_dinheiro_lancamentos";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."cardsahu";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."cardsaltoxv";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."entradas_mercadoria";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."lancamentos_financeiros";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."movimentacoes_estoque";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."producao_realizada";






GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";









































































































































































































GRANT ALL ON FUNCTION "public"."audit_log_trigger"() TO "anon";
GRANT ALL ON FUNCTION "public"."audit_log_trigger"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."audit_log_trigger"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_deleted_profile"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_deleted_profile"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_deleted_profile"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_total_vales"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_total_vales"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_total_vales"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_user_password"("target_user_id" "uuid", "new_password" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."update_user_password"("target_user_id" "uuid", "new_password" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_user_password"("target_user_id" "uuid", "new_password" "text") TO "service_role";

































GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."Checklist" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."Checklist" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."Checklist" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Checklist_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Checklist_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Checklist_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."Vales" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."Vales" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."Vales" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Vales_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Vales_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Vales_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."Vouchers" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."Vouchers" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."Vouchers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Vouchers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Vouchers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Vouchers_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."afericao_porcao" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."afericao_porcao" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."afericao_porcao" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."audit_logs" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."audit_logs" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."audit_logs" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."cadastro_insumos" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."cadastro_insumos" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."cadastro_insumos" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."cadastro_produtos" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."cadastro_produtos" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."cadastro_produtos" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."caixa_dinheiro_lancamentos" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."caixa_dinheiro_lancamentos" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."caixa_dinheiro_lancamentos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."caixa_dinheiro_lancamentos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."caixa_dinheiro_lancamentos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."caixa_dinheiro_lancamentos_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."cardsahu" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."cardsahu" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."cardsahu" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."cardsaltoxv" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."cardsaltoxv" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."cardsaltoxv" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."categorias_financeiras" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."categorias_financeiras" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."categorias_financeiras" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."clientes_food_service" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."clientes_food_service" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."clientes_food_service" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."contas" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."contas" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."contas" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."contas_fixas" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."contas_fixas" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."contas_fixas" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."contas_pagar_receber" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."contas_pagar_receber" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."contas_pagar_receber" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."entradas_mercadoria" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."entradas_mercadoria" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."entradas_mercadoria" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."feriados_globais" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."feriados_globais" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."feriados_globais" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."feriados_trabalhados" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."feriados_trabalhados" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."feriados_trabalhados" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."ficha_tecnica" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."ficha_tecnica" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."ficha_tecnica" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."fornecedores" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."fornecedores" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."fornecedores" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."frequencia" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."frequencia" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."frequencia" TO "service_role";



GRANT ALL ON SEQUENCE "public"."frequencia_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."frequencia_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."frequencia_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."historico_colaborador" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."historico_colaborador" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."historico_colaborador" TO "service_role";



GRANT ALL ON SEQUENCE "public"."historico_colaborador_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."historico_colaborador_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."historico_colaborador_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."historico_crm" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."historico_crm" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."historico_crm" TO "service_role";



GRANT ALL ON SEQUENCE "public"."historico_crm_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."historico_crm_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."historico_crm_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."historico_pagamentos_vt_vr" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."historico_pagamentos_vt_vr" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."historico_pagamentos_vt_vr" TO "service_role";



GRANT ALL ON SEQUENCE "public"."historico_pagamentos_vt_vr_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."historico_pagamentos_vt_vr_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."historico_pagamentos_vt_vr_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."inventario_insumos" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."inventario_insumos" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."inventario_insumos" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."lancamentos_financeiros" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."lancamentos_financeiros" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."lancamentos_financeiros" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."lista_compras_manual" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."lista_compras_manual" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."lista_compras_manual" TO "service_role";



GRANT ALL ON SEQUENCE "public"."lista_compras_manual_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."lista_compras_manual_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."lista_compras_manual_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."movimentacoes_estoque" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."movimentacoes_estoque" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."movimentacoes_estoque" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."notificacao_lojas" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."notificacao_lojas" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."notificacao_lojas" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."ordem_producao" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."ordem_producao" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."ordem_producao" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."pedidos_food_service" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."pedidos_food_service" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."pedidos_food_service" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pedidos_food_service_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pedidos_food_service_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pedidos_food_service_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."producao_realizada" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."producao_realizada" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."producao_realizada" TO "service_role";



GRANT ALL ON SEQUENCE "public"."producao_realizada_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."producao_realizada_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."producao_realizada_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."produtos_vale" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."produtos_vale" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."produtos_vale" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."profiles" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."profiles" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."profiles" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."salgados_inventory" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."salgados_inventory" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."salgados_inventory" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "service_role";































