export const GELATO_FLAVORS = [
  'Abacate',
  'Abacaxi com Hortelã e Gengibre',
  'Avelâ',
  'Banana Água',
  'Banana Nevada',
  'Banoffe',
  'Baunilha',
  'Caqui',
  'Caramelo Salgado',
  'Castanha do Pará',
  'Cheesecake de Frutas Vermelhas',
  'Cheseecake de Amora',
  'Choco Malte',
  'Chocolate',
  'Chocolate Branco com Maracujá',
  'Chocolate com Avelã',
  'Chocolate Supreme',
  'Chocolate Turco',
  'Cocada',
  'Coco',
  'Creme Brulèe',
  'Cupuaçu',
  'Danoninho',
  'Doce de Leite',
  'Dolce Mocha',
  'Don Vitto',
  'Frutas Vermelhas',
  'Gengibre',
  'Hortelã com Chocolate',
  'Iogurte com Amarena',
  'Iogurte com Laranja',
  'Iogurte com Maracujá',
  'Iogurte Grego',
  'Jabuticaba',
  'Kinder',
  'Leite Condensado com Morango',
  'Leite Ninho com Nutella',
  'Lemon Pie',
  'Limão Rosa',
  'Limão Siciliano',
  'Limão Tahiti',
  'Macadâmia',
  'Manga',
  'Manjericão',
  'Maracujá',
  'Melancia',
  'Melão',
  'Milho Verde',
  'Mocha',
  'Morango',
  'Morango ao Leite c/ Stracciatella',
  'Nozes c/ Doce de Leite',
  'Paçoca com Chocolate',
  'Paçoquinha',
  'Pannacotta',
  'Pera',
  'Pêssego',
  'Pistache',
  'Prestígio',
  'Romeu e Julieta',
  'Sete Belo',
  'Stracciatella',
  'Tangerina',
  'Torta Belga',
  'Torta de Laranja',
  'Uva',
].sort();
