export const GELATO_FLAVORS = [
  'Abacate',
  'Abacaxi com Hortelã e Gengibre',
  'Banana Nevada',
  'Banoffe',
  'Baunilha',
  'Café',
  'Caramelo Salgado',
  'Cheesecake de Frutas Vermelhas',
  'Chocolate',
  'Chocolate Branco com Maracujá',
  'Cocada',
  'Coco Diet',
  'Coco com Doce de Leite',
  'Danoninho',
  'Doce de Leite',
  'Dolce Mocha',
  'Don Vitto',
  'Frutas Vermelhas',
  'Hortelã com Chocolate',
  'Iogurte com Amarena',
  'Iogurte com Laranja',
  'Kinder',
  'Leite Condensado com Morango',
  'Leite Ninho com Nutella',
  'Lemon Pie',
  'Limão Tahiti',
  'Macadâmia',
  'Manga',
  'Maracujá',
  'Melancia',
  'Milho Verde',
  'Mocha',
  'Morango',
  'Paçoca com Chocolate',
  'Pistache',
  'Romeu e Julieta',
  'Sete Belo',
  'Stracciatella',
  'Tangerina',
  'Torta Belga',
  'Uva',
].sort();
