export const Sabores = [
  { value: "Chocolate Belga", label: "Chocolate Belga" },
  { value: "Pistache", label: "Pistache" },
  { value: "Ninho com Nutella", label: "Ninho com Nutella" },
  { value: "Morango (Sorbet)", label: "Morango (Sorbet)" },
  { value: "Doce de Leite", label: "Doce de Leite" },
  { value: "Baunilha", label: "Baunilha" },
  { value: "Coco", label: "Coco" },
  { value: "Paçoca", label: "Paçoca" },
  { value: "Maracujá (Sorbet)", label: "Maracujá (Sorbet)" },
  { value: "Limão Siciliano (Sorbet)", label: "Limão Siciliano (Sorbet)" },
  { value: "Bacio di Latte", label: "Bacio di Latte" },
  { value: "Brownie", label: "Brownie" },
  { value: "Cookies & Cream", label: "Cookies & Cream" },
  { value: "Amarena", label: "Amarena" },
  { value: "Iogurte com Amora", label: "Iogurte com Amora" },
  { value: "Chocolate 70%", label: "Chocolate 70%" },
  { value: "Manga (Sorbet)", label: "Manga (Sorbet)" },
  { value: "Caramelo Salgado", label: "Caramelo Salgado" },
  { value: "Mentinha", label: "Mentinha" },
  { value: "Fior di Latte", label: "Fior di Latte" },
  { value: "Ferrero Rocher", label: "Ferrero Rocher" },
  { value: "Kinder Bueno", label: "Kinder Bueno" },
  { value: "Rafaello", label: "Rafaello" },
  { value: "Torta de Limão", label: "Torta de Limão" },
  { value: "Banana com Nutella", label: "Banana com Nutella" },
  { value: "Café", label: "Café" },
  { value: "Cheesecake de Frutas Vermelhas", label: "Cheesecake de Frutas Vermelhas" },
  { value: "Milho Verde", label: "Milho Verde" },
  { value: "Abacaxi com Hortelã", label: "Abacaxi com Hortelã" },
  { value: "Açaí", label: "Açaí" },
];
