-- Script de inserção para cadastro_insumos

INSERT INTO public.cadastro_insumos (nome, nome_simples_unitario, tipo, fornecedor_padrao, quantidade_conversao, unidade_conversao, custo_considerado, custo_considerado_unitario, ativo, ordem)
VALUES
('Gelato - Kg', 'Gelato - Kg', 'Insumos', 'Fábrica', 1, 'Kg', NULL, NULL, TRUE, 1),
('Pote Kraft 80ml - c/ 50un', 'Pote Kraft 80ml', 'Insumos', 'Nazapack', 50, 'Unidade', NULL, NULL, TRUE, 2),
('Pote Kraft 120ml - c/ 50un', 'Pote Kraft 120ml', 'Insumos', 'Nazapack', 50, 'Unidade', NULL, NULL, TRUE, 3),
('Ki-Cascão Conny - c/ 120un', 'Cascão', 'Insumos', 'Marmikok', 120, 'Unidade', NULL, NULL, TRUE, 4),
('Ki-Casquinha Conny - c/ 240un', 'Casquinha', 'Insumos', 'Marmikok', 240, 'Unidade', NULL, NULL, TRUE, 5),
('Pote Kraft 480ml - c/ 50un', 'Pote Kraft 480ml', 'Insumos', 'FNS Cups', 50, 'Unidade', NULL, NULL, FALSE, 6),
('Pote Kraft 550ml - c/ 25un', 'Pote Kraft 550ml', 'Insumos', 'FNS Cups', 25, 'Unidade', NULL, NULL, TRUE, 7),
('Tampa p/ Pote Kraft 550ml - c/ 25un', 'Tampa p/ Pote Kraft 550ml', 'Insumos', 'FNS Cups', 25, 'Unidade', NULL, NULL, TRUE, 8),
('Tampa p/ Pote Kraft 480ml - c/ 50un', 'Tampa p/ Pote Kraft 480ml', 'Insumos', 'FNS Cups', 50, 'Unidade', NULL, NULL, FALSE, 9),
('Pázinha Curta Branca - c/ 500un', 'Pázinha Curta Branca', 'Insumos', 'Marmikok', 500, 'Unidade', NULL, NULL, TRUE, 10),
('Guardanapo 20x20 - c/ 100un', 'Guardanapo 20x20', 'Insumos', 'Marmikok', 100, 'Unidade', NULL, NULL, TRUE, 11),
('Pote 200ml Descartável - c/ 50un', '', 'Insumos', 'Marmikok', 50, 'Unidade', NULL, NULL, TRUE, 12),
('Tampa p/ Pote 200ml - c/ 50un', '', 'Insumos', 'Marmikok', 50, 'Unidade', NULL, NULL, TRUE, 13),
('Copo 300ml Descartável - c/ 100un', '', 'Insumos', 'Marmikok', 100, 'Unidade', NULL, NULL, TRUE, 14),
('Copo Papel Preto Parede Simples 110ml - c/ 50un', 'Copo de Papel Preto Parede Simples 110ml', 'Insumos', 'Sete Embalagens', 50, 'Unidade', NULL, NULL, TRUE, 15),
('Copo Papel Preto Parede Dupla 270ml - c/ 25un', 'Copo de Papel Preto Parede Dupla 270ml', 'Insumos', 'Sete Embalagens', 25, 'Unidade', NULL, NULL, TRUE, 16),
('Embalagem Waffle Cama - c/ 50un', '', 'Insumos', '', 50, 'Unidade', NULL, NULL, TRUE, 17),
('Embalagem Waffle Luva - c/ 50un', '', 'Insumos', '', 50, 'Unidade', NULL, NULL, TRUE, 18),
('Sacola P - 26x25x12cm - c/ 20un', 'Sacola P - 26x25x12cm', 'Insumos', 'Nobelpack', 20, 'Unidade', NULL, NULL, TRUE, 19),
('Sacola PP - 25x21x10cm - c/ 20un', 'Sacola PP - 25x21x10cm', 'Insumos', 'Nobelpack', 20, 'Unidade', NULL, NULL, TRUE, 20),
('Café em Grão - 1kg', 'Café em Grão', 'Insumos', 'Astoria', 1, 'Kg', NULL, NULL, TRUE, 21),
('Cappuccino em Pó - 1kg', 'Cappuccino em Pó', 'Insumos', 'Astoria', 1, 'Kg', NULL, NULL, TRUE, 22),
('Chocolate Quente em Pó - 1kg', 'Chocolate Quente em Pó', 'Insumos', 'Net Coffe', 1, 'Kg', NULL, NULL, TRUE, 23),
('Cacau em pó 50% - 500gr (NESTLÉ) "mocha"', '', 'Insumos', '', 0.5, 'Kg', NULL, NULL, TRUE, 24),
('Leite UHT Integral - 1kg', 'Leite UHT Integral', 'Insumos', 'Mercado', 1, 'Kg', NULL, NULL, TRUE, 25),
('Nutella Pote - 650gr', 'Nutella', 'Insumos', 'Santo Antônio', 0.65, 'Kg', NULL, NULL, TRUE, 26),
('Doce de Leite - 350gr', 'Doce de Leite', 'Insumos', 'Condor', 0.35, 'Kg', NULL, NULL, TRUE, 27),
('Sanduíche de Carne - 1un', '', 'Salgados', 'Cassinele', 1, 'Unidade', NULL, NULL, TRUE, 28),
('Sanduíche de Frango - 1un', '', 'Salgados', 'Cassinele', 1, 'Unidade', NULL, NULL, TRUE, 29),
('Sanduíche de Pernil - 1un', '', 'Salgados', 'Cassinele', 1, 'Unidade', NULL, NULL, TRUE, 30),
('Sanduíche de Mortadela - 1un', '', 'Salgados', 'Cassinele', 1, 'Unidade', NULL, NULL, TRUE, 31),
('Sanduíche de Parma - 1un', '', 'Salgados', 'Cassinele', 1, 'Unidade', NULL, NULL, TRUE, 32),
('Quiche de Alho Poró - 1un', '', 'Salgados', 'Cassinele', 1, 'Unidade', NULL, NULL, TRUE, 33),
('Quiche Capresse - 1un', '', 'Salgados', 'Cassinele', 1, 'Unidade', NULL, NULL, TRUE, 34),
('Quiche Lorraine - 1un', '', 'Salgados', 'Cassinele', 1, 'Unidade', NULL, NULL, TRUE, 35),
('Guardanapo Interfolhado 10x20 ROSA - c/ 5.000un', '', 'Insumos', 'Marmikok', 5000, 'Unidade', NULL, NULL, TRUE, 36),
('Guardanapo Sache Delivery - c/ 1.000un', '', 'Insumos', 'Mercado Livre', 1000, 'Unidade', NULL, NULL, FALSE, 37),
('Papel Interfolhado 20x20 Branco 2 Dobras - c/ 1.000un', '', 'Insumos', 'Marmikok', 1000, 'Unidade', NULL, NULL, TRUE, 38),
('Pote 100ml Descartável - c/ 100un', '', 'Insumos', 'Marmikok', 100, 'Unidade', NULL, NULL, TRUE, 39),
('Pote de Isopor 120ml - c/ 20un', '', 'Insumos', '', 20, 'Unidade', NULL, NULL, TRUE, 40),
('Tampa p/ Pote 120ml - c/ 100un', '', 'Insumos', '', 100, 'Unidade', NULL, NULL, TRUE, 41),
('Pote p/ Molho 30ml Galvanotek G695 - c/ 10un', '', 'Insumos', 'Armazem das Embalagens', 10, 'Unidade', NULL, NULL, TRUE, 42),
('Pote p/ Molho 60ml Galvanotek G697 - c/ 20un', '', 'Insumos', 'Armazem das Embalagens', 20, 'Unidade', NULL, NULL, TRUE, 43),
('Tampa p/ Copo Papel 110ml - c/ 50un', '', 'Insumos', 'Sete Embalagens', 50, 'Unidade', NULL, NULL, TRUE, 44),
('Tampa  p/ Copo Papel 270ml - 62mm - c/ 50un', '', 'Insumos', 'Sete Embalagens', 50, 'Unidade', NULL, NULL, TRUE, 45),
('Long Drink Transparente 325ml - "Copo Soda Italiana"', 'Copo p/ Soda Italiana', 'Insumos', '', 1, 'Unidade', NULL, NULL, TRUE, 46),
('Canudo com Mexedor - c/ 100un', 'Canudo p/ Soda Italiana', 'Insumos', '', 100, 'Unidade', NULL, NULL, TRUE, 47),
('Canudo Biodegradável - c/ 100un', '', 'Insumos', 'Marmikok', 100, 'Unidade', NULL, NULL, TRUE, 48),
('Mechedor de Café Simples 11cm - c/ 500un', '', 'Insumos', 'Marmikok', 500, 'Unidade', NULL, NULL, TRUE, 49),
('Garfo Forte - c/ 50un (STRAWPLAST)', '', 'Insumos', '', 50, 'Unidade', NULL, NULL, TRUE, 50),
('Faca Forte - c/ 50un (STRAWPLAST)', '', 'Insumos', '', 50, 'Unidade', NULL, NULL, TRUE, 51),
('Colher Forte - c/ 50un (STRAWPLAST)', '', 'Insumos', '', 50, 'Unidade', NULL, NULL, TRUE, 52),
('Saco de Plástico p/ Talher 4cm x 23cm - c/ 1.000un', '', 'Insumos', '', 1000, 'Unidade', NULL, NULL, TRUE, 53),
('Saco de Papel p/ Talher 6cm x 26cm - c/ 500un', '', 'Insumos', '', 500, 'Unidade', NULL, NULL, TRUE, 54),
('Filtro de Papel p/ Café n102 - c/ 30un', '', 'Insumos', '', 30, 'Unidade', NULL, NULL, TRUE, 55),
('Caixa Kraft p/ Porção Grande - c/ 25un', '', 'Insumos', 'Comercial Barbante e Papel', 25, 'Unidade', NULL, NULL, TRUE, 56),
('Embalagem de Cachorro Quente - c/ 100un', '', 'Insumos', '', 100, 'Unidade', NULL, NULL, TRUE, 57),
('Papel Barreira 20x20 c/ 1.000 folhas', '', 'Insumos', 'Mercado Livre', 1000, 'Unidade', NULL, NULL, TRUE, 58),
('Saco Kraft Delivery Liso SOS 15kg - c/ 100un', '', 'Insumos', 'Sete Embalagens', 100, 'Unidade', NULL, NULL, TRUE, 59),
('Luva de vinil sem pó - Tamanho M - c/100un', '', 'Insumos', 'Marmikok', 100, 'Unidade', NULL, NULL, FALSE, 60),
('Luva de vinil sem pó - Tamanho G - c/ 100un', '', 'Insumos', 'Marmikok', 100, 'Unidade', NULL, NULL, FALSE, 61),
('Plástico Filme 28cm x 100m', 'Plástico Filme', 'Insumos', '', 1, 'Unidade', NULL, NULL, TRUE, 62),
('Touca Descartável - c/ 100un', '', 'Insumos', 'Mercado Livre', 100, 'Unidade', NULL, NULL, TRUE, 63),
('Máscara Descartável - c/ 100un', '', 'Insumos', 'Mercado Livre', 100, 'Unidade', NULL, NULL, TRUE, 64),
('Etiquetas Adesivas Brancas Grande - 50x30mm', '', 'Insumos', 'Marmikok', 1, 'Unidade', NULL, NULL, TRUE, 65),
('Etiqueta Adesivo Redonda TP19 Preta - (PIMACO) - c/ 200un', '', 'Insumos', 'Kalunga', 200, 'Unidade', NULL, NULL, TRUE, 66),
('Grampo p/ Grampeador', '', 'Insumos', 'Papelaria', 1, 'Unidade', NULL, NULL, TRUE, 67),
('Bobina Impressora - 80mm', '', 'Insumos', 'Mercado Livre', 1, 'Unidade', NULL, NULL, TRUE, 68),
('Bobina Maquininha', '', 'Insumos', 'Mercado Livre', 1, 'Unidade', NULL, NULL, TRUE, 69),
('Durex', '', 'Insumos', '', 1, 'Unidade', NULL, NULL, TRUE, 70),
('Sachê de Açúcar', '', 'Insumos', '', 1, 'Unidade', NULL, NULL, TRUE, 71),
('Sachê de Adoçante', '', 'Insumos', '', 1, 'Unidade', NULL, NULL, TRUE, 72),
('Abaixador de Língua Madeira c/ 100un  (THEOTO)', '', 'Insumos', 'Orto Curitiba', 100, 'Unidade', NULL, NULL, FALSE, 73),
('Xarope de Maça Verde - 250ml', 'Xarope Monin', 'Insumos', '', 0.25, 'Kg', NULL, NULL, TRUE, 74),
('Xarope de Framboesa - 250ml', '', 'Insumos', '', 0.25, 'Kg', NULL, NULL, TRUE, 75),
('Xarope de Tangerina - 250ml', '', 'Insumos', '', 0.25, 'Kg', NULL, NULL, TRUE, 76),
('Xarope de Baunilha - 250ml', '', 'Insumos', '', 0.25, 'Kg', NULL, NULL, TRUE, 77),
('Xarope de Caramelo - 250ml', '', 'Insumos', '', 0.25, 'Kg', NULL, NULL, TRUE, 78),
('Xarope de Maça Verde - 750ml', '', 'Insumos', '', 0.75, 'Kg', NULL, NULL, TRUE, 79),
('Xarope de Framboesa - 750ml', '', 'Insumos', '', 0.75, 'Kg', NULL, NULL, TRUE, 80),
('Xarope de Tangerina - 750ml', '', 'Insumos', '', 0.75, 'Kg', NULL, NULL, TRUE, 81),
('Xarope de Baunilha - 750ml', '', 'Insumos', '', 0.75, 'Kg', NULL, NULL, TRUE, 82),
('Xarope de Caramelo - 750ml', '', 'Insumos', '', 0.75, 'Kg', NULL, NULL, TRUE, 83),
('Saco de Lixo 20 Litros Preto Micra 4 - c/ 100un', '', 'Material de Limpeza', 'Super Brilho', 100, 'Unidade', NULL, NULL, TRUE, 84),
('Saco de Lixo 40 Litros Preto Micra 4 - c/ 100un', '', 'Material de Limpeza', 'Super Brilho', 100, 'Unidade', NULL, NULL, TRUE, 85),
('Saco de Lixo 60 Litros Preto Micra 8 - c/ 100un', '', 'Material de Limpeza', 'Super Brilho', 100, 'Unidade', NULL, NULL, TRUE, 86),
('Desinfetante Pato', 'Desinfetante Pato', 'Material de Limpeza', 'Mercado', 1, 'Unidade', NULL, NULL, TRUE, 87),
('Veja Multi Uso 500ml', '', 'Material de Limpeza', 'Super Brilho', 1, 'Unidade', NULL, NULL, TRUE, 88),
('Papel Higiênico - FD - 12 Rolos/30mt', '', 'Material de Limpeza', 'Super Brilho', 1, 'Unidade', NULL, NULL, TRUE, 89),
('Álcool Líquido 70% - 5 Litros', '', 'Material de Limpeza', 'Super Brilho', 1, 'Unidade', NULL, NULL, TRUE, 90),
('Álcool em Gel 70% - 5 Litros', '', 'Material de Limpeza', 'Super Brilho', 1, 'Unidade', NULL, NULL, TRUE, 91),
('Detergente Neutro - 5 Litros', '', 'Material de Limpeza', 'Super Brilho', 1, 'Unidade', NULL, NULL, TRUE, 92),
('Esponja Multiuso Dupla Face AM/VD', '', 'Material de Limpeza', 'Super Brilho', 1, 'Unidade', NULL, NULL, TRUE, 93),
('Pano Multiuso - 28cm x 25mt', '', 'Material de Limpeza', 'Super Brilho', 1, 'Unidade', NULL, NULL, TRUE, 94),
('Detergente Neutro - 500ml', '', 'Material de Limpeza', 'Super Brilho', 1, 'Unidade', NULL, NULL, TRUE, 95),
('Água Sanitária - 5 Litros', '', 'Material de Limpeza', 'Super Brilho', 1, 'Unidade', NULL, NULL, TRUE, 96),
('Sabão em Pó Omo - 2.2kg', '', 'Material de Limpeza', 'Super Brilho', 2.2, 'kg', NULL, NULL, TRUE, 97),
('Álcool Líquido 70% - 1 Litro', '', 'Material de Limpeza', '', 1, 'Unidade', NULL, NULL, TRUE, 98),
('Água Crystal - Garrafa - (500ml)', 'Água Crystal - Garrafa - (500ml)', 'Bebidas', 'Coca Cola', 1, 'Unidade', NULL, NULL, TRUE, 99),
('Água Crystal Com Gás - Garrafa - (500ml)', 'Água Crystal Com Gás - Garrafa - (500ml)', 'Bebidas', 'Coca Cola', 1, 'Unidade', NULL, NULL, TRUE, 100),
('Coca Cola - Lata - (350ml)', 'Coca Cola - Lata - (350ml)', 'Bebidas', 'Coca Cola', 1, 'Unidade', NULL, NULL, TRUE, 101),
('Coca Cola Sem Açucar - Lata - (350ml)', 'Coca Cola Sem Açucar - Lata - (350ml)', 'Bebidas', 'Coca Cola', 1, 'Unidade', NULL, NULL, TRUE, 102),
('Schweppes Citrus - Lata - (350ml)', 'Schweppes Citrus - Lata - (350ml)', 'Bebidas', 'Distribuidor de Bebidas', 1, 'Unidade', NULL, NULL, TRUE, 103),
('Schweppes Tônica - Lata - (350ml)', 'Schweppes Tônica - Lata - (350ml)', 'Bebidas', 'Distribuidor de Bebidas', 1, 'Unidade', NULL, NULL, FALSE, 104),
('Fanta Laranja - Lata - (350ml)', 'Fanta Laranja - Lata - (350ml)', 'Bebidas', 'Distribuidor de Bebidas', 1, 'Unidade', NULL, NULL, TRUE, 105),
('Fanta Uva - Lata - (350ml)', 'Fanta Uva - Lata - (350ml)', 'Bebidas', 'Distribuidor de Bebidas', 1, 'Unidade', NULL, NULL, TRUE, 106),
('Fanta Guaraná - Lata - (350ml)', 'Fanta Guaraná - Lata - (350ml)', 'Bebidas', 'Distribuidor de Bebidas', 1, 'Unidade', NULL, NULL, TRUE, 107),
('Sprite - Lata - (350ml)', 'Sprite - Lata - (350ml)', 'Bebidas', 'Distribuidor de Bebidas', 1, 'Unidade', NULL, NULL, TRUE, 108),
('Chá Matte Leao - Copo - (300ml)', 'Chá Matte Leao - Copo - (300ml)', 'Bebidas', 'Distribuidor de Bebidas', 1, 'Unidade', NULL, NULL, TRUE, 109),
('Chá Matte Leao Limão - Copo - (300ml)', 'Chá Matte Leao Limão - Copo - (300ml)', 'Bebidas', 'Distribuidor de Bebidas', 1, 'Unidade', NULL, NULL, TRUE, 110),
('Chá Matte Leao Guaraná Power - Copo - (300ml)', 'Chá Matte Leao Guaraná Power - Copo - (300ml)', 'Bebidas', 'Distribuidor de Bebidas', 1, 'Unidade', NULL, NULL, TRUE, 111),
('Chá Matte Leao Guaraná Power Açai - Copo - (300ml)', 'Chá Matte Leao Guaraná Power Açai - Copo - (300ml)', 'Bebidas', 'Distribuidor de Bebidas', 1, 'Unidade', NULL, NULL, TRUE, 112),
('Suco Del Valle Pêssego - Lata - (290ml)', 'Suco Del Valle Pêssego - Lata - (290ml)', 'Bebidas', 'Distribuidor de Bebidas', 1, 'Unidade', NULL, NULL, TRUE, 113),
('Suco Del Valle Uva - Lata - (290ml)', 'Suco Del Valle Uva - Lata - (290ml)', 'Bebidas', 'Distribuidor de Bebidas', 1, 'Unidade', NULL, NULL, TRUE, 114),
('Suco Del Valle Goiaba - Lata - (290ml)', 'Suco Del Valle Goiaba - Lata - (290ml)', 'Bebidas', 'Distribuidor de Bebidas', 1, 'Unidade', NULL, NULL, TRUE, 115),
('Suco Del Valle Manga - Lata - (290ml)', 'Suco Del Valle Manga - Lata - (290ml)', 'Bebidas', 'Distribuidor de Bebidas', 1, 'Unidade', NULL, NULL, TRUE, 116),
('Suco Del Valle Maracujá - Lata - (290ml)', 'Suco Del Valle Maracujá - Lata - (290ml)', 'Bebidas', 'Distribuidor de Bebidas', 1, 'Unidade', NULL, NULL, TRUE, 117),
('Suco Del Valle Limonada Classic - Lata - (290ml)', 'Suco Del Valle Limonada Classic - Lata - (290ml)', 'Bebidas', 'Distribuidor de Bebidas', 1, 'Unidade', NULL, NULL, TRUE, 118),
('Suco Del Valle Limonada Pink - Lata - (290ml)', 'Suco Del Valle Limonada Pink - Lata - (290ml)', 'Bebidas', 'Distribuidor de Bebidas', 1, 'Unidade', NULL, NULL, TRUE, 119),
('Sache Açucar - c/ 400un', '', 'Insumos', '', 400, 'Unidade', NULL, NULL, TRUE, 120),
('Sache Adoçante - c/ 1.000un', '', 'Insumos', '', 1000, 'Unidade', NULL, NULL, TRUE, 121),
('Lacre Ifood', '', 'Insumos', '', 1, 'Unidade', NULL, NULL, TRUE, 122),
('Xarope de Maple Syrup - 816ml', 'Xarope de Maple Syrup', 'Insumos', 'Mercado Livre', 0.816, 'Kg', NULL, NULL, TRUE, 123),
('Leite Condensado - 395gr', '', 'Insumos', '', 0.395, 'Kg', NULL, NULL, TRUE, 124),
('Recheio de chocolate Branco Nestlé Galak - 1kg', 'Recheio de chocolate Branco Nestlé Galak', 'Insumos', 'Mercado Livre', 1, 'Kg', NULL, NULL, TRUE, 125),
('Paçoquita Embalada - 1un', 'Paçoca Unidade', 'Insumos', '', 1, 'Unidade', NULL, NULL, TRUE, 126),
('Mini Óreo - 35gr', 'Mini Óreo - 35gr - Unidade', 'Insumos', '', 1, 'Unidade', NULL, NULL, TRUE, 127),
('Mini Disqueti - Chocolate ao Leite - 11gr', 'Mini Disqueti - 11gr - Unidade', 'Insumos', '', 1, 'Unidade', NULL, NULL, TRUE, 128),
('Morango Bandeja - c/ 250gr', 'Morango', 'Insumos', 'Kalunga', 0.25, 'kg', NULL, NULL, TRUE, 129),
('Banana', 'Banana', 'Insumos', '', 1, 'Kg', NULL, NULL, TRUE, 130),
('Massa de Waffle', 'Massa de Waffle', 'Insumos', 'Fábrica MH', 1, 'Unidade', NULL, NULL, TRUE, 131),
('Brownie', 'Brownie', 'Insumos', 'Fábrica MH', 1, 'Unidade', NULL, NULL, TRUE, 132),
('Geleia de Amora - 700gr', 'Geleia de Amora', 'Insumos', 'Fábrica MH', 0.7, 'Kg', NULL, NULL, TRUE, 133);
